server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/commerce
    driver-class-name: org.mariadb.jdbc.Driver
    username: commerce_user
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
